void parse_var_section();
void parse_id_list();
void parse_body();
void parse_stmt_list();
void parse_stmt();
void parse_assign_stmt();
struct InstructionNode* parse_for_assign_stmt();
void parse_expr();
void parse_for_expr(struct InstructionNode*);
void parse_primary();
void parse_op();
void parse_for_op(struct InstructionNode*);
void parse_output_stmt();
void parse_input_stmt();
void parse_while_stmt();
void parse_if_stmt();
struct InstructionNode* parse_condition(struct InstructionNode*);
void parse_relop();
void parse_switch_stmt();
void parse_for_stmt();
void parse_case_list(std::string);
void parse_case(std::string);
void parse_default_case();
void parse_inputs();
void parse_num_list();
void parse_condition();